apiVersion: vs.axis-dev.io/v1
kind: AssemblyLine
metadata:
  name: demo-app-deploy
spec:
  params:
    - name: gitRevision
      description: ""
  results:
    - name: apiEndpoint
      value: $(stages.resolve-ip.results.ipAddress)
  artifacts:
    - path: .
  stages:
    - name: build
      spec:
        deployment:
          app: qvs-demo-app
          name: gcp-dev
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
          - name: imageTag
            value: $(inputs.gitRevision)
        pipeline: qvs-demo-app-build
    - name: deploy
      spec:
        deployment:
          app: qvs-demo-app
          name: gcp-dev
        params:
          - name: gitRevision
            value: $(inputs.gitRevision)
          - name: imageName
            value: $(stages.build.results.imageFullNameTag)
        pipeline: qvs-demo-app-deploy
      runAfter:
        - build
    - name: resolve-ip
      spec:
        deployment:
          app: qvs-demo-app
          name: gcp-dev
        params: []
        pipeline: qvs-demo-app-resolve-ip-address-after-deploy
      runAfter:
        - deploy
